global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: pulse-api
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          service: api

  - job_name: pulse-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          service: worker

  - job_name: pulse-scheduler
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8082"]
        labels:
          service: scheduler
